/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface GradeEstimation {
  'gradeLabel' : string,
  'normalizedScore' : bigint,
  'edgeClarityScore' : bigint,
}
export interface ProcessResult {
  'valueReport' : ValueBreakdown,
  'gradeOutcome' : GradeEstimation,
  'message' : string,
}
export interface ValueBreakdown {
  'scoreRarityBonus' : bigint,
  'gradeMultiplier' : bigint,
  'gradeModDependency' : bigint,
  'estimatedValue' : bigint,
  'baselineValue' : bigint,
  'normalizationAdjustment' : bigint,
  'gradeBonus' : bigint,
  'combinedRarityBonus' : bigint,
}
export interface _SERVICE {
  'configureBaseline' : ActorMethod<[string, bigint], undefined>,
  'processCoin' : ActorMethod<[string, bigint, bigint, bigint], ProcessResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];