/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ValueBreakdown = IDL.Record({
  'scoreRarityBonus' : IDL.Nat,
  'gradeMultiplier' : IDL.Nat,
  'gradeModDependency' : IDL.Nat,
  'estimatedValue' : IDL.Nat,
  'baselineValue' : IDL.Nat,
  'normalizationAdjustment' : IDL.Nat,
  'gradeBonus' : IDL.Nat,
  'combinedRarityBonus' : IDL.Nat,
});
export const GradeEstimation = IDL.Record({
  'gradeLabel' : IDL.Text,
  'normalizedScore' : IDL.Nat,
  'edgeClarityScore' : IDL.Nat,
});
export const ProcessResult = IDL.Record({
  'valueReport' : ValueBreakdown,
  'gradeOutcome' : GradeEstimation,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  'configureBaseline' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'processCoin' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
      [ProcessResult],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ValueBreakdown = IDL.Record({
    'scoreRarityBonus' : IDL.Nat,
    'gradeMultiplier' : IDL.Nat,
    'gradeModDependency' : IDL.Nat,
    'estimatedValue' : IDL.Nat,
    'baselineValue' : IDL.Nat,
    'normalizationAdjustment' : IDL.Nat,
    'gradeBonus' : IDL.Nat,
    'combinedRarityBonus' : IDL.Nat,
  });
  const GradeEstimation = IDL.Record({
    'gradeLabel' : IDL.Text,
    'normalizedScore' : IDL.Nat,
    'edgeClarityScore' : IDL.Nat,
  });
  const ProcessResult = IDL.Record({
    'valueReport' : ValueBreakdown,
    'gradeOutcome' : GradeEstimation,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    'configureBaseline' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'processCoin' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
        [ProcessResult],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };